# Generated by Django 3.2.2 on 2021-07-15 15:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='city',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
